# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/sbrd/api/token
Accept: application/json; utf-8
Content-Type: application/json; utf-8

{
  "username": "gty",
  "password": "123456"
}

###

GET http://localhost:8080/sbrd/api/student?sort=createdDate,desc&page=0&size=5
Accept: application/json; utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

###

POST http://localhost:8080/sbrd/api/student
Accept: application/json; utf-8
Content-Type: application/json; utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

{
  "name": "Taylor Swift 😒😒😒😒",
  "age": 30,
  "gender": "Female",
  "balance": "123.23"
}

###

GET http://localhost:8080/sbrd/api/student/100
Accept: application/json; utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

###

GET http://localhost:8080/sbrd/api/github
Accept: application/json; utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

###

DELETE http://localhost:8080/sbrd/api/student/1
Accept: application/json; utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

###

GET http://localhost:8080/sbrd/api/files/test.txt
Accept: application/octet-stream
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

###

POST http://localhost:8080/sbrd/api/files/upload?fileAdditionalInfo=WTF
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json; utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlzcyI6InNwcmluZy1ib290LXJlYWN0aXZlLWRlbW8iLCJ1c2VybmFtZSI6Imd0eSJ9.i13DyrCgn2stoyxVuR3n7bslx798s-i6SjKxjabCQsr51jIvNi6JzZWG1PCi2dcxaum5ASzzcPOkiwf48w0H1g

--WebAppBoundary
Content-Disposition: form-data; name="uploadFile"; filename="test.txt"

< ./demo.http

--WebAppBoundary--

###
