sbrd.service-host: localhost

sbrd.postgresql-host: ${sbrd.service-host}
sbrd.redis-host: ${sbrd.service-host}
sbrd.rabbitmq-host: ${sbrd.service-host}
sbrd.kafka-host: ${sbrd.service-host}

logging:
  level:
    web: debug
    sql: debug
    org.gty.demo: debug

spring:
  codec:
    log-request-details: true
  jpa:
    show-sql: false

feign:
  logging:
    level: full
