service-host: localhost

postgresql-host: ${service-host}
redis-host: ${service-host}
rabbitmq-host: ${service-host}
kafka-host: ${service-host}

logging:
  level:
    web: debug
    sql: debug
#   org.gty.demo: debug

spring:
  http:
    log-request-details: true
  jpa:
    show-sql: false
