management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://${sbrd.postgresql-host}:5432/db_sbrd
    driver-class-name: org.postgresql.Driver
    username: gty
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    type: redis
    redis:
      time-to-live: 2d
#     key-prefix: 'spring-boot-reactive-demo:cache:'
  redis:
    host: ${sbrd.redis-host}
    password: 123456
    timeout: 100ms
  data:
    redis:
      repositories:
        enabled: false
  rabbitmq:
    host: ${sbrd.rabbitmq-host}
  kafka:
    bootstrap-servers: ${sbrd.kafka-host}:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    template:
      default-topic: demo-topic
  session:
    store-type: redis
  gson:
    serialize-nulls: true
  webflux:
    base-path: /sbrd
    format:
      date: iso
      date-time: iso
      time: iso
  lifecycle:
    timeout-per-shutdown-phase: 1s

sbrd:
  storage-content: "These violent delights have violent ends."

feign:
  logging:
    level: basic
