service-host: localhost

postgresql-host: ${service-host}
redis-host: ${service-host}
rabbitmq-host: ${service-host}
kafka-host: ${service-host}

logging:
  level:
    org.gty.demo: debug
    org.gty.demo.mapper: trace
