version: "3"

services:
  spring-boot-reactive-demo:
    build:
      context: ./build/
      args:
        LAYERED_JAR_FILE: "*.jar"
    environment:
      JDK_JAVA_OPTIONS: -XX:+UseShenandoahGC
#     JDK_JAVA_OPTIONS: -XX:+UseZGC
      TZ: UTC
      SPRING_PROFILES_ACTIVE: dev-docker
    networks:
      - appnetwork
    ports:
      - "8080:8080"
    volumes:
      - ./app-logs:/var/log/app-logs
    depends_on:
      - "postgres"
      - "redis"
      - "rabbitmq"
      - "kafka"
  postgres:
    image: library/postgres:alpine
    environment:
      POSTGRES_DB: db_sbrd
      POSTGRES_USER: gty
      POSTGRES_PASSWORD: 123456
      TZ: UTC
      PGTZ: UTC
    networks:
      - appnetwork
    volumes:
      - ./db/data:/var/lib/postgresql/data
  redis:
    image: library/redis:alpine
    networks:
      - appnetwork
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
  rabbitmq:
    image: library/rabbitmq:alpine
    networks:
      - appnetwork
  zookeeper:
    image: library/zookeeper:latest
    networks:
      - appnetwork
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 17
      KAFKA_CREATE_TOPICS: "demo-topic:2:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - "zookeeper"
    networks:
      - appnetwork
networks:
  appnetwork:
